name: cd

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:

  job1:
    name: job1
    runs-on: ubuntu-20.04
    steps:

      - name: step1
        run: echo "cd - step1"

      - name: step2
        env:
          WORKFLOW_FILE_NAME: 'cd.yaml'
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: ./cancel.py
