name: cd

on:
  push:
    branches:
      - main
    tags:
      - 'v0.1.*'
      - 'v0.2.*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  job1:
    name: job1
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout application repository
        uses: actions/checkout@v2

      - name: Step1
        run: |
          env | grep GITHUB | sort
