name: staging

on:
  push:
    branches:
      - main

jobs:
  job1:
    name: job1
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout application repository
        uses: actions/checkout@v2

      - name: Step1
        run: |
          env | grep GITHUB | sort

      - name: Trigger Production workflow
        env:
          GITHUB_TOKEN: ${{ secrets.APP1_GITHUB_TOKEN }}
        run: ./trigger_production.sh
